version: "2.4"

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 3000:1314
    volumes:
      - .:/opt/app
      # use node_modules in the container
      - /opt/app/node_modules
